import fs from "node:fs";
import path from "node:path";

const DIR_PATH = "@content/assets/photo";

function generateRow(fileName: string, fileNameNoExt: string): string {
  return `import ${fileNameNoExt} from "${DIR_PATH}/${fileName}";\n`;
}

function main(): void {
  const fileNameList = fs.readdirSync("./assets/photo").sort();
  const fileNameListNoExt = fileNameList.map(
    fileName => path.parse(fileName).name,
  );

  const dataList: string[] = [];

  for (let i = 0; i < fileNameList.length; i++) {
    dataList.push(
      generateRow(fileNameList[i] ?? "", fileNameListNoExt[i] ?? ""),
    );
  }

  dataList.push("\n// THIS FILE IS AUTO GENERATED BY SCRIPT.\n");
  dataList.push("\nexport const CONTENTS = [\n");
  dataList.push(`\t${fileNameListNoExt.join(",\n\t")}`);
  dataList.push(",\n];\n");

  fs.writeFileSync("./_photo/data.ts", dataList.join(""), {
    encoding: "utf8",
  });
}

if (import.meta.main) {
  main();
}
