name: create-pr
on:
  schedule:
    - cron: "0 23 * * 1"
  workflow_dispatch:

jobs:
  contents:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-contents-${{ github.ref }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Install Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2
        with:
          bun-version-file: "package.json"

      - name: Install dependencies
        run: bun install

      - name: run generate:photo
        run: bun generate:photo

      - name: run generate:book
        run: bun generate:book

      - run: bun biome:fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: "create-pull-request/s-contents-summary"
          commit-message: "s-contents-summary updates"
          title: "contents: s-contents-summary updates"
          body: |
            This is an update PR of s-contents-summary.

  gh-stars:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-gh-stars-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run Python script
        run: python gh-export-stars/src/main.py --user s-hirano-ist --output ./portfolio/gh-stars.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: "create-pull-request/gh-stars"
          commit-message: "contents: update gh-stars.json"
          title: "contents: update gh-stars.json"
          body: |
            This is an update PR of gh-stars.json.
