name: create-pr
on:
  schedule:
    - cron: "0 23 * * 1"
  workflow_dispatch:

jobs:
  contents:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-contents-${{ github.ref }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: true

      - name: Install Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: "22.14.0"

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          run_install: false

      - name: Get pnpm directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"

      - name: Cache dependencies
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: pnpm i --frozen-lockfile

      - name: run script
        run: pnpm fetch-news
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          USERNAME_TO_EXPORT: ${{ secrets.USERNAME_TO_EXPORT }}

      - run: pnpm generate:photo
      - run: pnpm generate:book
      - run: pnpm license:summary
      - run: bash checkLicense.sh

      - run: pnpm fmt:fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: "create-pull-request/contents"
          commit-message: "contents: update contents"
          title: "contents: update news, photo, books, and license."
          body: |
            This is an update PR of contents.

  gh-stars:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-gh-stars-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run Python script
        run: python gh-export-stars/src/main.py --user s-hirano-ist --output ./src/content/portfolio/gh-stars.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: "create-pull-request/gh-stars"
          commit-message: "contents: update gh-stars.json"
          title: "contents: update gh-stars.json"
          body: |
            This is an update PR of gh-stars.json.
