name: create-pr
on:
  schedule:
    - cron: "0 23 * * 1"
  workflow_dispatch:

jobs:
  contents:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-contents-${{ github.ref }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4
        with:
          run_install: false

      - name: Get pnpm directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"

      - name: Cache dependencies
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: pnpm i --frozen-lockfile

      - name: run script
        run: pnpm fetch-news
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          USERNAME_TO_EXPORT: ${{ secrets.USERNAME_TO_EXPORT }}

      - run: pnpm generate:photo
      - run: pnpm generate:book
      - run: pnpm license:summary
      - run: bash checkLicense.sh

      - run: pnpm fmt:fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: "create-pull-request/contents"
          commit-message: "contents: update contents"
          title: "contents: update news, photo, books, and license."
          body: |
            This is an update PR of contents.

  gh-stars:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-gh-stars-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run Python script
        run: python gh-export-stars/src/main.py --user s-hirano-ist --output ./src/content/portfolio/gh-stars.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: "create-pull-request/gh-stars"
          commit-message: "contents: update gh-stars.json"
          title: "contents: update gh-stars.json"
          body: |
            This is an update PR of gh-stars.json.
