name: github-actions-lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml
  workflow_dispatch:

jobs:
  github-actions-lint:
    permissions:
      contents: read
      pull-requests: write
    uses: s-hirano-ist/s-templates/.github/workflows/github-actions-lint.yaml@f11acc9a3a19bcc5654ef94fbe408191b7e25378 # main
