name: github-actions-lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml
  workflow_dispatch:

jobs:
  github-actions-lint:
    permissions:
      contents: read
      pull-requests: write
    uses: s-hirano-ist/s-templates/.github/workflows/github-actions-lint.yaml@aad54d0bfd573cda93c12f676eba2878c7fcce7e # main
