name: github-actions-lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml
  workflow_dispatch:

jobs:
  github-actions-lint:
    permissions:
      contents: read
      pull-requests: write
    uses: s-hirano-ist/s-templates/.github/workflows/github-actions-lint.yaml@ee962fc7608385b6e88b841d12d700db112d5872
