name: github-actions-lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml
  workflow_dispatch:

jobs:
  github-actions-lint:
    permissions:
      contents: read
      pull-requests: write
    uses: s-hirano-ist/s-templates/.github/workflows/github-actions-lint.yaml@bb41da04c6e230e4ca92cf441663f2568b044cd3 # main
