name: renovate-config-validator

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/renovate-config-validator.yaml"

jobs:
  renovate-config-validator:
    permissions:
      contents: read
    uses: s-hirano-ist/s-templates/.github/workflows/renovate-config-validator.yaml@aad54d0bfd573cda93c12f676eba2878c7fcce7e # main
