name: renovate-config-validator

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/renovate-config-validator.yaml"

jobs:
  renovate-config-validator:
    permissions:
      contents: read
    uses: s-hirano-ist/s-templates/.github/workflows/renovate-config-validator.yaml@f11acc9a3a19bcc5654ef94fbe408191b7e25378 # main
