name: renovate-config-validator

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/renovate-validator.yaml"

jobs:
  renovate-config-validator:
    uses: s-hirano-ist/s-templates/.github/workflows/renovate-config-validator.yaml@main
    secrets: inherit
