name: renovate-config-validator

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/renovate.json5"
      - ".github/workflows/renovate-config-validator.yaml"

jobs:
  renovate-config-validator:
    permissions:
      contents: read
    uses: s-hirano-ist/s-templates/.github/workflows/renovate-config-validator.yaml@9f835cbeb6b2457d3fc0cf3a8bf7b906a8af639b
