name: update-github-stars
on:
  schedule:
    - cron: "0 23 * * 1"
jobs:
  create_pull_request:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run Python script
        run: python gh-export-stars/src/main.py --user s-hirano-ist --output ./src/content/portfolio/gh-stars.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: "contents: update gh-stars.json"
          title: "contents: update gh-stars.json"
          body: |
            This is an update PR of gh-stars.json.
