name: update-github-stars
on:
  schedule:
    - cron: "0 23 * * 1"
jobs:
  create_pull_request:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run Python script
        run: python gh-export-stars/src/main.py --user s-hirano-ist --output ./src/content/portfolio/gh-stars.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          branch: "create-pull-request/update-gh-stars"
          commit-message: "contents: update gh-stars.json"
          title: "contents: update gh-stars.json"
          body: |
            This is an update PR of gh-stars.json.
