name: vrt
on:
  deployment_status:
jobs:
  screenshots:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview'
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24.14.1"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - run: pnpm i --frozen-lockfile
      - run: pnpm exec playwright install
      - run: pnpm snapshots:update
        env:
          BASE_URL: https://s-hirano.com/
      - run: pnpm snapshots
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
      - name: Upload failed screenshots
        if: failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: vrt-failed-screenshots-${{ github.sha }}
          path: test-results
